---
title: "Love_ECC_subset_visualize"
output: html_document
---

To generate figure S1

```{r,message=FALSE}
library(tidyverse)
library(iCOBRA)
```

Load data

```{r}
if(TRUE) {
    load(file='02_love_et_al_benchmark_DTU_analysis_ECC_tpm_subset.Rdata')
  
    loveBenchmark <- c(
        loveDtuBenchmark_quasiBinomial,
        loveDtuBenchmark_DoubleExpSeq,
        loveDtuBenchmark_limmaDiffsplice,
        loveDtuBenchmark_edgeRdiffsplice,
        loveDtuBenchmark_DEXSeq,
        loveDtuBenchmark_DRIMSeq,
        loveDtuBenchmark_NBSplice,
        loveDtuBenchmark_BANDITS
    )

    ### Remove empty enteries (due to not tested - aka to many samples for reasonable runtime)
    loveBenchmark  <- loveBenchmark[which(
        sapply(loveBenchmark, function(x) ! is.null(x$dtuAnalysis))
    )]
    
    rm(loveDtuBenchmark_quasiBinomial,
        loveDtuBenchmark_DoubleExpSeq,
        loveDtuBenchmark_limmaDiffsplice,
        loveDtuBenchmark_edgeRdiffsplice,
        loveDtuBenchmark_DEXSeq,
        loveDtuBenchmark_DRIMSeq,
        loveDtuBenchmark_NBSplice,
        loveDtuBenchmark_BANDITS)
    invisible(gc())
}

truth_file <- read.table("/Users/jg/Desktop/PhD/DTU_project/Github/dtuPaper/Data/Love_data/truth_Love.txt")
```

```{r}
get_pvalues <- function(dataset,nrep,nmethods) {

  get_all_txs <- function(dataset,nrep){
  
    all_txs <- c()
 
    for (i in 1:nrep) {
      current_txs <- as.character(dataset[[i]]$dtuAnalysis$TXNAME)
      all_txs <- c(all_txs, current_txs)
      all_txs <- unique(all_txs)
    }
    return(all_txs)
  }

  all_txs <- get_all_txs(dataset,nrep)
  pvalues <- matrix(data=NA, nrow=length(all_txs), ncol=nmethods*nrep)
  rownames(pvalues) <- all_txs
  
  for (i in 1:(nmethods*nrep)) {
    pvalues_new <- data.frame(dataset[[i]]$dtuAnalysis$p_value)
    rownames(pvalues_new) <- dataset[[i]]$dtuAnalysis$TXNAME
    colnames(pvalues_new) <- names(dataset)[i]

    pvalues[,i] <- pvalues_new[match(rownames(pvalues),rownames(pvalues_new)),1]
  }
  
  pvalues <- apply(pvalues, 2, as.numeric)
  rownames(pvalues) <- all_txs
  pvalues <- as.data.frame(pvalues)
  pvalues <- pvalues[order(rownames(pvalues)),]
  
  # colnames(pvalues) <- c("quasiBinomial", "BANDITS", "limmaDiffsplice", "edgeRDiffsplice", "DoubleExpSeq")
  
  colnames(pvalues) <- c("quasiBinomial", "DoubleExpSeq", "limmaDiffsplice", "edgeRDiffsplice", "DEXSeq", "DRIMSeq", "NBSplice", "BANDITS")

  return(pvalues)
}
```



```{r}
visualize_datasets <- function(dataset,nFilters,nSampleSizes,nrep,nmethods) {
  
  nPlots <- nFilters * nSampleSizes
  print(paste("This function will generate",nPlots, "plots"))
  
  ##  We must select the correct dataframes from the list, based on the list names
  selection <- c("3_rep_._filterLenient","6_rep_._filterLenient","10_rep_._filterLenient","3_rep_._filterStringent","6_rep_._filterStringent","10_rep_._filterStringent")
  
  ## Generate and store the data for the plots
  resList <- c()
  for (j in 1:nPlots) {
    print(j) # print progress
    
    loveBenchmark_current <- loveBenchmark[grepl(selection[j], names(loveBenchmark))]
    
    # omit edgeR total
    loveBenchmark_current_1 <- loveBenchmark_current[c(1,4,7,10,13,16,19,22)]
    loveBenchmark_current_2 <- loveBenchmark_current[c(2,5,8,11,14,17,20,23)]
    loveBenchmark_current_3 <- loveBenchmark_current[c(3,6,9,12,15,18,21,24)]
    
    pvalues_1 <- get_pvalues(loveBenchmark_current_1,1,nmethods)
    pvalues_2 <- get_pvalues(loveBenchmark_current_2,1,nmethods)
    pvalues_3 <- get_pvalues(loveBenchmark_current_3,1,nmethods)
    
    pvalues_1[is.na(pvalues_1)] <- 1
    pvalues_2[is.na(pvalues_2)] <- 1
    pvalues_3[is.na(pvalues_3)] <- 1
    
    pvalues_1 <- pvalues_1[,c(2:8)]
    pvalues_2 <- pvalues_2[,c(2:8)]
    pvalues_3 <- pvalues_3[,c(2:8)]

    truth_file_current_1 <- truth_file[truth_file$TXNAME %in% rownames(pvalues_1),]
    truth_file_current_1 <- truth_file_current_1[order(truth_file_current_1$TXNAME),]
    truth_file_current_2 <- truth_file[truth_file$TXNAME %in% rownames(pvalues_2),]
    truth_file_current_2 <- truth_file_current_2[order(truth_file_current_2$TXNAME),]
    truth_file_current_3 <- truth_file[truth_file$TXNAME %in% rownames(pvalues_3),]
    truth_file_current_3 <- truth_file_current_3[order(truth_file_current_3$TXNAME),]
    
    rownames(pvalues_1) <- paste0(rownames(pvalues_1), "_1")
    rownames(pvalues_2) <- paste0(rownames(pvalues_2), "_2")
    rownames(pvalues_3) <- paste0(rownames(pvalues_3), "_3")

    rownames(truth_file_current_1) <- truth_file_current_1$TXNAME <- rownames(pvalues_1)
    rownames(truth_file_current_2) <- truth_file_current_2$TXNAME <- rownames(pvalues_2)
    rownames(truth_file_current_3) <- truth_file_current_3$TXNAME <- rownames(pvalues_3)
    
    pvalues_full <- rbind(pvalues_1,pvalues_2,pvalues_3)
    truth_file_full <- rbind(truth_file_current_1,truth_file_current_2,truth_file_current_3)

    cobra <- COBRAData(pval = pvalues_full, truth = truth_file_full)
    cobra <- calculate_adjp(cobra)
    cobra1perf <- calculate_performance(cobra, binary_truth = "truth", cont_truth = "none", splv = "none", aspects = c("fdrtpr", "fdrtprcurve", "overlap"))
    
    cobraplot <- prepare_data_for_plot(cobra1perf, colorscheme = "Dark2", facetted = TRUE)
    
    new_col <- c(rep(c("#CC79A7","#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#999999"),4),rep("white",16))
    names(new_col) <- names(cobraplot@plotcolors)
    cobraplot@plotcolors <- new_col
  
    plot_full <- plot_fdrtprcurve(cobraplot, xaxisrange = c(0, 0.35), yaxisrange = c(0,0.85))
    
    titles <- c("3 versus 3 - edgeR filter - scaledTPM","6 versus 6 - edgeR filter - scaledTPM","10 versus 10 - edgeR filter - scaledTPM","3 versus 3 - DRIMSeq filter - scaledTPM","6 versus 6 - DRIMSeq filter - scaledTPM","10 versus 10 - DRIMSeq filter - scaledTPM")
    current_title <- titles[j]

    plot_full <- plot_full + 
      ggtitle(current_title) +
      theme(strip.background = element_blank(),
            strip.text.x = element_blank(),
            plot.title = element_text(size=10),
            axis.text.x = element_text(size = 10),
            axis.text.y = element_text(size = 10),
            axis.title.x = element_text(size = 10),
            axis.title.y = element_text(size = 10))
    
    png(paste("/Users/jg/Desktop/PhD/DTU_project/Github/dtuPaper/Results/Love_ECC_benchmark/plot_icobra_subset_tpm_figS1_", j, ".png", sep = ""),
          width     = 5.5,
          height    = 4.5,
          units     = "in",
          res       = 200,
          pointsize = 4) # start export

    print(plot_full)
    dev.off()
  }
}
```

```{r}
visualize_datasets(dataset=loveBenchmark,
                   nFilters=2,
                   nSampleSizes=3,
                   nrep=3,
                   nmethods=8)
```






