---
title: "Gtex_DTU_filter"
output: html_document
---

Load all DTU methods

```{r, message=FALSE}
### Libraries
library(edgeR)
library(limma)
library(DEXSeq)
library(DRIMSeq)
library(DoubleExpSeq)
library(NBSplice)
library(qbDTU)

### Functions for running each method
if(TRUE) {
  
  qbDTU_DTU <- function(countData, tx2gene, sampleData, quiet = FALSE){
        
        colnames(tx2gene)[1:2] <- c("isoform_id", "gene_id")
        group <- factor(sampleData$condition)
        design <- model.matrix(~0+group)
        
        sumExp <- SummarizedExperiment::SummarizedExperiment(assays=list(counts=countData), colData = sampleData, rowData = tx2gene)

        metadata(sumExp)$formula <- ~0+group
        
        sumExp <- qbDTU::fitQB.method(sumExp,
                       speed = FALSE,
                       parallel = TRUE,
                       BPPARAM = BiocParallel::bpparam(),
                       verbose = TRUE
                      )
        
        L <- matrix(0, ncol = 1, nrow = ncol(design))
        rownames(L) <- colnames(design)
        colnames(L) <- c("AvsB")
        L[1:2,] <- c(-1,1)
        
        sumExp <- qbDTU::topTable(object = sumExp, contrasts = L, plot=F)
        
        output <- data.frame(rownames(countData))
        rownames(output) <- rownames(countData)
        colnames(output) <- "TXNAME"
        
        output$GENEID <- tx2gene[match(output$TXNAME,tx2gene$TXNAME),"GENEID"]
        
        result <- rowData(sumExp)[["fitQBResult_AvsB"]]
        
        output$tvalue <- result$t
        output$p_value_raw <- result$pval
        output$FDR_raw <- result$regular_FDR
        output$p_value <- result$empirical_pval
        output$FDR <- result$empirical_FDR

        localRes <- output
        
        return(localRes)
    }
    
    ## DoubleExpSeq
    DoubleExpSeq_DTU <- function(countData, tx2gene, sampleData,quiet=FALSE) {
      
        # get tx2gene in better format
        geneForEachTx <- tx2gene$GENEID[match(rownames(countData),tx2gene$TXNAME)]
        groupID <- as.character(geneForEachTx)
      
        ## get the "total" counts
        stopifnot(class(countData)[1] %in% c("matrix", "data.frame"))
        countData <- as.matrix(countData)
        stopifnot(class(groupID) %in% c("character", "factor"))
        stopifnot(length(groupID) == nrow(countData))

        if( ! quiet) {print("Calculating offsets")}
        forCycle <- split(1:nrow(countData), as.character(groupID))
        all <- lapply(forCycle, function(i) {
            sct <- countData[i, , drop = FALSE]
            rs <- t(sapply(1:nrow(sct), function(r) colSums(sct[, , drop = FALSE])))
            rownames(rs) <- rownames(sct)
            rs
        })
        all <- do.call(rbind, all)
        stopifnot(all(rownames(countData) %in% rownames(all)))
        all <- all[rownames(countData), ]
        totalCount <- all
        
        condition <- as.factor(sampleData$condition)
        
        mDouble <- suppressWarnings(DBGLM1(y = countData,
                  m = totalCount,
                  groups = condition))
        
        pvalDouble <- mDouble$All[,"pVal"]
        dispDouble <- mDouble$All[,"Model.Disp"]
        
        localRes <- data.frame(rownames(countData))
        rownames(localRes) <- rownames(countData)
        colnames(localRes) <- "TXNAME"
        
        localRes$GENEID <- tx2gene[match(localRes$TXNAME,tx2gene$TXNAME),"GENEID"]
        localRes$p_value <- pvalDouble ## here I am only returning p-values, could also look into storing logFCs and FDRs
        localRes$disp <- dispDouble

        return(localRes)
    }
    
    ### Limma
    limma_diffsplice_DTU <- function(countData, tx2gene, sampleData) {
        # Make design
        design = model.matrix(~condition, data=sampleData)

        geneForEachTx <- tx2gene$GENEID[match(rownames(countData),tx2gene$TXNAME)]
        y <- DGEList(counts = countData, group=as.data.frame(sampleData)$condition, genes = geneForEachTx)

        y <- calcNormFactors(y)

        v <- voom(y, design, plot=FALSE)
        fit <- lmFit(v, design)

        ex <- limma::diffSplice(fit, geneid = "genes")

        limmaRes <- topSplice(ex, coef=2, test="t", number = Inf)

        ### Massage result
        localRes <- limmaRes
        localRes$TXNAME <- rownames(localRes)
        rownames(localRes) <- NULL

        colnames(localRes)[which(colnames(localRes) == 'genes')] <- 'GENEID'

        localRes <- localRes[,c(
            which( colnames(localRes) == 'TXNAME'),
            which( colnames(localRes) == 'GENEID'),
            which( ! colnames(localRes) %in% c('TXNAME','GENEID'))
        )]

        colnames(localRes)[which(colnames(localRes) == 'P.Value')] <- 'p_value'

        return(localRes)
    }
    
        
    ## edgeR_diffsplice
    edgeR_diffsplice_DTU <- function(countData, tx2gene, sampleData) {
      
        y <- DGEList(counts = countData, group=as.data.frame(sampleData)$condition)
        y <- calcNormFactors(y)
      
        design <- model.matrix(~condition, data=sampleData)
      
        y <- estimateDisp(y, design = design)
        fit <- glmFit(y, design = design) ## glmQLfit --> very poor results
      
        dtuEdgeR <- edgeR::diffSpliceDGE(
            glmfit = fit,
            exonid = tx2gene$TXNAME,
            geneid = tx2gene$GENEID,
            coef = "conditionb",
            verbose = FALSE
        )
      
        localRes <- topSpliceDGE(
            dtuEdgeR,
            test = 'exon',
            number = Inf
        )

        rownames(localRes) <- NULL
        colnames(localRes)[which(colnames(localRes) == 'GeneID')] <- 'GENEID'
        colnames(localRes)[which(colnames(localRes) == 'ExonID')] <- 'TXNAME'

        localRes <- localRes[,c(
            which( colnames(localRes) == 'TXNAME'),
            which( colnames(localRes) == 'GENEID'),
            which( ! colnames(localRes) %in% c('TXNAME','GENEID'))
        )]

        colnames(localRes)[which(colnames(localRes) == 'P.Value')] <- 'p_value'

        return(localRes)
    }

    ### DEXSeq
    DEXSeq_DTU <- function(countData, tx2gene, sampleData) {
        # get tx2gene in better format
        geneForEachTx <- tx2gene$GENEID[match(rownames(countData),tx2gene$TXNAME)]

        countData <- round(countData)

        dxd <- DEXSeqDataSet(countData = countData,
                             sampleData = sampleData,
                             design = ~ sample + exon + condition:exon,
                             featureID = rownames(countData),
                             groupID = as.character(geneForEachTx))

        dxd <- estimateSizeFactors(dxd)
        ## note that estimating dispersions takes some time!
        print("estimating the dispersions")
        dxd <- estimateDispersions(dxd)

        print("testing for DEU")
        dxd <- testForDEU(dxd, reducedModel=~ sample + exon)

        print("Getting the results")
        dxr <- DEXSeqResults(dxd)

        ### Massage result
        localRes <- as.data.frame(dxr)
        localRes <- localRes[,c('featureID','groupID','exonBaseMean','dispersion','stat','pvalue','padj')]
        colnames(localRes)[1:2] <- c('TXNAME','GENEID')
        rownames(localRes) <- NULL

        colnames(localRes)[which(colnames(localRes) == 'pvalue')] <- 'p_value'
        colnames(localRes)[which(colnames(localRes) == 'padj')] <- 'FDR'

        return(localRes)
    }
    
    ### DRIMSeq
    DRIMSeq_DTU <- function(countData, tx2gene, sampleData) {
        ## To make DRIMSeq analysis reproducible
        set.seed(123)
      
        # get tx2gene in better format
        countData <- round(countData)
        countData <- as.data.frame(countData)

        geneForEachTx <- tx2gene$GENEID[match(rownames(countData),tx2gene$TXNAME)]

        countData$gene_id <- geneForEachTx
        countData$feature_id <- row.names(countData)
        rownames(countData) <- c()

        d <- dmDSdata(counts = countData, samples = sampleData)

        design <- model.matrix(~ condition, data = DRIMSeq::samples(d))

        print("dmPrecision")
        d <- dmPrecision(d, design = design)

        print("dmFit")
        d <- dmFit(d, design = design, verbose = 1)

        print("dmTest")
        d <- dmTest(d, coef = 2, verbose = 1)

        ### Massage result
        localRes <- DRIMSeq::results(d, level = "feature")[, c(
            'feature_id',
            'gene_id',
            'lr',
            'df',
            'pvalue',
            'adj_pvalue'
        )]
        colnames(localRes)[1:2] <- c('TXNAME','GENEID')

        colnames(localRes)[which(colnames(localRes) == 'pvalue')] <- 'p_value'
        colnames(localRes)[which(colnames(localRes) == 'adj_pvalue')] <- 'FDR'

        return(localRes)
    }
    
    ## NBSplice
    NBSplice_DTU <- function(countData, tx2gene, sampleData,quiet=FALSE) {
        
        if( ! quiet) {print("Working")}
      
        sampleData$condition <- as.factor(sampleData$condition)
        geneIso <- as.data.frame(tx2gene[,c(2,1)])
        rownames(geneIso) <- geneIso[,2]
        colnames(geneIso) <- c("gene_id", "isoform_id")
        
        colnames(sampleData) <- c("id", "condition")
        rownames(sampleData) <- sampleData$id
        sampleData$condition <- as.factor(sampleData$condition)

        colName<-"condition"

        countData <- round(countData)
        
        myIsoDataSet <- IsoDataSet(countData, sampleData, colName, geneIso)
        myDSResults <- suppressWarnings(NBTest(myIsoDataSet, colName, test="F")) ## other option is chisq
        localRes <- myDSResults@results
        localRes <- localRes[,c(1,2,7)]
        colnames(localRes) <- c("TXNAME", "GENEID", "p_value")
        
        return(localRes)
    }
}
```  

```{r}
### Set up parralel execution
if(TRUE) {
    nrCores <- 2

    if(nrCores != 1) {
        doParallel <- TRUE
        doProgress <- 'none'

        library(doMC)
        registerDoMC(cores = nrCores)
    } else {
        doParallel <- FALSE
        doProgress <- 'text'
    }
}
```

Run the analysis for all 9 methods on all (24) datasets

```{r}
### Run DTU analysis on Love et al Benchmark data - done
## Note that all runtimes are for the full simulation

if(TRUE) {
    ### Load benchmark data
    load(file='01_gtex_benchmark_data_count.Rdata')
  
  
    ### Combine
    names(gtexBenchmarkDataLenient)   <- paste0(names(gtexBenchmarkDataLenient)  , '_filterLenient')
    names(gtexBenchmarkDataStringent) <- paste0(names(gtexBenchmarkDataStringent), '_filterStringent')

    gtexBenchmarkData <- c(
        gtexBenchmarkDataLenient,
        gtexBenchmarkDataStringent
    )
    
    length(gtexBenchmarkData) # 24
    
    ### Run DTU analysis on benchmark data
    
    print("start quasiBinomial")
    
    # quasiBinomial
    tStart <- Sys.time()
    suppressWarnings(gtexDtuBenchmark_quasiBinomial <- plyr::llply(
        .data = gtexBenchmarkData,
        .inform = TRUE,
        .fun = function(localData) {
            ### Perform DTU analysis
            t0 <- Sys.time()
            localRes <- qbDTU_DTU(
                countData  = localData$data,
                tx2gene    = localData$metaInfo,
                sampleData = localData$design
            )
            testTime <- as.numeric( difftime(Sys.time(), t0, units = 'secs') )

            ### Massage
            localRes$gene_modified <- localData$metaInfo$gene_modified[match(
                localRes$TXNAME, localData$metaInfo$TXNAME
            )]

            ### Return result
            return(
                list(
                    dtuAnalysis = localRes,
                    runtime = testTime
                )
            )
        }
    ))
    difftime(Sys.time(), tStart)
    
    print("start DoubleExpSeq")

    gtexDtuBenchmark_DoubleExpSeq <- plyr::llply(
        .data = gtexBenchmarkData,
        .parallel = doParallel,
        .progress = doProgress,
        .inform = TRUE,
        .fun = function(localData) {
            ### Perform DTU analysis
            t0 <- Sys.time()
            localRes <- DoubleExpSeq_DTU(
                countData  = localData$data,
                tx2gene    = localData$metaInfo,
                sampleData = localData$design,
                quiet=FALSE
            )
            testTime <- as.numeric(difftime(Sys.time(), t0, units = 'secs') )

            ### Massage
            localRes$gene_modified <- localData$metaInfo$gene_modified[match(
                localRes$TXNAME, localData$metaInfo$TXNAME
            )]

            ### Return result
            return(
                list(
                    dtuAnalysis = localRes,
                    runtime = testTime
                )
            )
        }
    )
    
    print("start limma diffsplice")

    # limma_diffsplice_DTU : Runtime - fast - done
    gtexDtuBenchmark_limmaDiffsplice <- plyr::llply(
        .data = gtexBenchmarkData,
        .parallel = doParallel,
        .progress = doProgress,
        .inform = TRUE,
        .fun = function(localData) {
            ### Perform DTU analysis
            t0 <- Sys.time()
            localRes <- limma_diffsplice_DTU(
                countData  = localData$data,
                tx2gene    = localData$metaInfo,
                sampleData = localData$design
            )
            testTime <- as.numeric( difftime(Sys.time(), t0, units = 'secs') )

            ### Massage
            localRes$gene_modified <- localData$metaInfo$gene_modified[match(
                localRes$TXNAME, localData$metaInfo$TXNAME
            )]

            ### Return result
            return(
                list(
                    dtuAnalysis = localRes,
                    runtime = testTime
                )
            )
        }
    )
    
    ## edgeR_diffsplice
    print("start edgeR_diffsplice")

    gtexDtuBenchmark_edgeRdiffsplice <- plyr::llply(
        .data = gtexBenchmarkData,
        .parallel = doParallel,
        .progress = doProgress,
        .inform = TRUE,
        .fun = function(localData) {
            ### Perform DTU analysis
            t0 <- Sys.time()
            localRes <- edgeR_diffsplice_DTU(
                countData  = localData$data,
                tx2gene    = localData$metaInfo,
                sampleData = localData$design
            )
            testTime <- as.numeric(difftime(Sys.time(), t0, units = 'secs') )

            ### Massage
            localRes$gene_modified <- localData$metaInfo$gene_modified[match(
                localRes$TXNAME, localData$metaInfo$TXNAME
            )]

            ### Return result
            return(
                list(
                    dtuAnalysis = localRes,
                    runtime = testTime
                )
            )
        }
    )
    
    print("start DEXSeq")

    # DEXSeq : Runtime - ~ 45 min on 30 cores - done
    tStart <- Sys.time()
    gtexDtuBenchmark_DEXSeq <- plyr::llply(
        .data = gtexBenchmarkData,
        .parallel = doParallel,
        .progress = doProgress,
        .inform = TRUE,
        .fun = function(localData) {
            
            if(ncol(localData$data) > 10) {
                return(NULL)
            }
          
            ### Perform DTU analysis
            t0 <- Sys.time()
            localRes <- DEXSeq_DTU(
                countData  = localData$data,
                tx2gene    = localData$metaInfo,
                sampleData = localData$design
            )
            testTime <- as.numeric(difftime(Sys.time(), t0, units = 'secs') )

            ### Massage
            localRes$gene_modified <- localData$metaInfo$gene_modified[match(
                localRes$TXNAME, localData$metaInfo$TXNAME
            )]

            ### Return result
            return(
                list(
                    dtuAnalysis = localRes,
                    runtime = testTime
                )
            )
        }
    )
    difftime(Sys.time(), tStart)
    
    print("start DRIMSeq")

    # DRIMseq - ~ 1.85 hrs on 30 cores - done
    ### Too slow on laptop --> run at night
    tStart <- Sys.time()
    gtexDtuBenchmark_DRIMSeq <- plyr::llply(
        .data = gtexBenchmarkData,
        .parallel = doParallel,
        .progress = doProgress,
        .inform = TRUE,
        .fun = function(localData) {
          
            if(ncol(localData$data) > 10) {
                return(NULL)
            }
          
            ### Perform DTU analysis
            t0 <- Sys.time()
            localRes <- DRIMSeq_DTU(
                countData  = localData$data,
                tx2gene    = localData$metaInfo,
                sampleData = localData$design
            )
            testTime <- as.numeric( difftime(Sys.time(), t0, units = 'secs') )

            ### Massage
            localRes$gene_modified <- localData$metaInfo$gene_modified[match(
                localRes$TXNAME, localData$metaInfo$TXNAME
            )]

            ### Return result
            return(
                list(
                    dtuAnalysis = localRes,
                    runtime = testTime
               )
           )
        }
    )
    difftime(Sys.time(), tStart)
    
     
    print("start NBSplice")

    gtexDtuBenchmark_NBSplice <- plyr::llply(
        .data = gtexBenchmarkData,
        .parallel = doParallel,
        .progress = doProgress,
        .inform = TRUE,
        .fun = function(localData) {
          
            if(ncol(localData$data) > 10) {
                  return(NULL)
            }
          
            ### Perform DTU analysis
            t0 <- Sys.time()
            localRes <- NBSplice_DTU(
                countData  = localData$data,
                tx2gene    = localData$metaInfo,
                sampleData = localData$design,
                quiet=FALSE
            )
            testTime <- as.numeric(difftime(Sys.time(), t0, units = 'secs') )

            ### Massage
            localRes$gene_modified <- localData$metaInfo$gene_modified[match(
                localRes$TXNAME, localData$metaInfo$TXNAME
            )]

            ### Return result
            return(
                list(
                    dtuAnalysis = localRes,
                    runtime = testTime
                )
            )
        }
    )

    ### add method name to list names for easy post-analysis
    names(gtexDtuBenchmark_quasiBinomial) <- paste0('quasiBinomial_'    , names(gtexDtuBenchmark_quasiBinomial))
    names(gtexDtuBenchmark_DoubleExpSeq)   <- paste0('DoubleExpSeq_'        , names(gtexDtuBenchmark_DoubleExpSeq))
    names(gtexDtuBenchmark_limmaDiffsplice) <- paste0('limma_diffsplice_', names(gtexDtuBenchmark_limmaDiffsplice))
    names(gtexDtuBenchmark_edgeRdiffsplice)   <- paste0('edgeR_diffsplice_'        , names(gtexDtuBenchmark_edgeRdiffsplice))
    names(gtexDtuBenchmark_DEXSeq)          <- paste0('DEXSeq_'         , names(gtexDtuBenchmark_DEXSeq))
    names(gtexDtuBenchmark_DRIMSeq)         <- paste0('DRIMSeq_'        , names(gtexDtuBenchmark_DRIMSeq))
    names(gtexDtuBenchmark_NBSplice)         <- paste0('NBSplice_'        , names(gtexDtuBenchmark_NBSplice))

    ### Save result
    save(gtexDtuBenchmark_quasiBinomial,
        gtexDtuBenchmark_limmaDiffsplice,
        gtexDtuBenchmark_edgeRdiffsplice,
        gtexDtuBenchmark_DoubleExpSeq,
        file='02_gtex_DTU_analysis_2017_count.Rdata'
    )
}
```




