---
title: "Tasic_getData_count"
output: html_document
---

Select the cells of interest for the single cell benchmark based on the Tasic dataset.

```{r}
metaData <- openxlsx::read.xlsx("/Users/jg/Desktop/PhD/DTU_project/Github/dtuPaper/Data/Tasic_data/Supplementary_Table_10_Full_Metadata.xlsx")

access <- read.csv2("/Users/jg/Desktop/PhD/DTU_project/Github/dtuPaper/Data/Tasic_data/GSE115746_accession_table.csv",sep = "\t")
```

```{r}
select <- metaData[which(metaData$brain_region == "ALM" & metaData$subclass == "Lamp5" & metaData$eye_condition=="Normal"),"sample_name"]

SRR_Select <- as.character(access[which(access$sample_name %in% select),"SRA_Run"])

cat(SRR_Select, file = "/Users/jg/Desktop/PhD/DTU_project/Github/dtuPaper/Data/Tasic_data/SRR_Select.txt",sep = "\n")
```

Next, we retrieve the required cells from GSE and quantify the the data using salmon (add code for bash later).

Next, we import the salmon quantification using the txImport package

```{r}
dir <- "/Volumes/ExternalDrive/DTU_project/Data/Tasic/salmon_Tasic_1"
samples <- read.table(file.path(dir, "SRR_select.txt"), header = FALSE)
head(samples)
```

```{r}
files <- file.path(dir, samples$V1, "quant.sf")
names(files) <- paste0("sample", 1:length(samples$V1))
all(file.exists(files))
```

```{r, message=FALSE}
library(AnnotationHub)
## Load the annotation resource.
ah <- AnnotationHub()

## Query for all available EnsDb databases
all <- query(ah, "EnsDb")

library(ensembldb)

ahEdb <- all[["AH75036"]] #for Mus musculus

txs <- transcripts(ahEdb)
```

```{r}
tx2gene <- as.data.frame(matrix(data = NA, nrow = length(txs), ncol = 2))
colnames(tx2gene) <- c("TXNAME","GENEID")
tx2gene$TXNAME <- txs$tx_id
tx2gene$GENEID <- txs$gene_id
```

```{r}
library(tximport)
quantsf <- tximport(files, type = "salmon", tx2gene = tx2gene, ignoreTxVersion = TRUE, countsFromAbundance = "no", txOut = TRUE)
```

```{r}
sum(quantsf$counts==0)/(sum(quantsf$counts==0)+sum(quantsf$counts!=0))
# 84.7% zeros on raw counts (no filter)
```

```{r}
saveRDS(quantsf$counts, file = "/Users/jg/Desktop/PhD/DTU_project/Github/dtuPaper/Data/Tasic_data/quantsf_counts")
```



