---
title: "Gtex_DTU_filter"
output: html_document
---

# Load all 7 DTU methods

In stead, source the DTU_methods.R script

```{r}
err <- try(library("here", character.only = TRUE), silent = TRUE)
if (class(err) == 'try-error') {
    install.packages("here", repos = "https://cloud.r-project.org")
    library("here", character.only = TRUE)
}
wd <- here()

source(file=paste0(wd,"/Performance_benchmarks/DTU_methods.R"))
```

# Set up parralel execution

```{r}
if(TRUE) {
    nrCores <- 2

    if(nrCores != 1) {
        doParallel <- TRUE
        doProgress <- 'none'

        library(doMC)
        registerDoMC(cores = nrCores)
    } else {
        doParallel <- FALSE
        doProgress <- 'text'
    }
}
```

# Run the analysis 

For all 9 methods on all (24) Gtex benchmark datasets
This code runs about ... on my laptop (MacBook Pro 2018, processor; 2,3 GHz Quad-Core Intel Core i5, 16GB RAM)

```{r}
### Load the benchmark datasets, which are output from 1_Gtex_prepare.Rmd
load(file=paste0(wd,'/Data/Gtex_workingData/02_GTEx_benchmark_datasets_count.Rdata'))
#load(file="/Users/jg/Desktop/paper_Data/Gtex_workingData/02_GTEx_benchmark_datasets_count.Rdata")

### Wrangle benchmark data
names(gtexBenchmarkDataLenient)   <- paste0(names(gtexBenchmarkDataLenient)  , '_filterLenient')
names(gtexBenchmarkDataStringent) <- paste0(names(gtexBenchmarkDataStringent), '_filterStringent')

gtexBenchmarkData <- c(
    gtexBenchmarkDataLenient,
    gtexBenchmarkDataStringent)

### Run DTU analysis on benchmark data
    
print("start satuRn")

tStart <- Sys.time()
suppressWarnings(gtexDtuBenchmark_satuRn <- plyr::llply(
    .data = gtexBenchmarkData,
    .inform = TRUE,
    .fun = function(localData) {
        ### Perform DTU analysis
        t0 <- Sys.time()
        localRes <- satuRn_DTU(
            countData  = localData$data,
            tx2gene    = localData$metaInfo,
            sampleData = localData$design
        )
        testTime <- as.numeric( difftime(Sys.time(), t0, units = 'secs') )

        ### Massage
        localRes$gene_modified <- localData$metaInfo$gene_modified[match(
            localRes$TXNAME, localData$metaInfo$TXNAME
        )]

        ### Return result
        return(
            list(
                dtuAnalysis = localRes,
                runtime = testTime
            )
        )
    }
))
difftime(Sys.time(), tStart)
    
print("start DoubleExpSeq")

tStart <- Sys.time()
gtexDtuBenchmark_DoubleExpSeq <- plyr::llply(
    .data = gtexBenchmarkData,
    .parallel = doParallel,
    .progress = doProgress,
    .inform = TRUE,
    .fun = function(localData) {
        ### Perform DTU analysis
        t0 <- Sys.time()
        localRes <- DoubleExpSeq_DTU(
            countData  = localData$data,
            tx2gene    = localData$metaInfo,
            sampleData = localData$design,
            quiet=FALSE
        )
        testTime <- as.numeric(difftime(Sys.time(), t0, units = 'secs') )

        ### Massage
        localRes$gene_modified <- localData$metaInfo$gene_modified[match(
            localRes$TXNAME, localData$metaInfo$TXNAME
        )]

        ### Return result
        return(
            list(
                dtuAnalysis = localRes,
                runtime = testTime
            )
        )
    }
)
difftime(Sys.time(), tStart)
    
print("start limma diffsplice")

tStart <- Sys.time()
gtexDtuBenchmark_limmaDiffsplice <- plyr::llply(
    .data = gtexBenchmarkData,
    .parallel = doParallel,
    .progress = doProgress,
    .inform = TRUE,
    .fun = function(localData) {
        ### Perform DTU analysis
        t0 <- Sys.time()
        localRes <- limma_diffsplice_DTU(
            countData  = localData$data,
            tx2gene    = localData$metaInfo,
            sampleData = localData$design
        )
        testTime <- as.numeric( difftime(Sys.time(), t0, units = 'secs') )

        ### Massage
        localRes$gene_modified <- localData$metaInfo$gene_modified[match(
            localRes$TXNAME, localData$metaInfo$TXNAME
        )]

        ### Return result
        return(
            list(
                dtuAnalysis = localRes,
                runtime = testTime
            )
        )
    }
)
difftime(Sys.time(), tStart)
    
print("start edgeR_diffsplice")

tStart <- Sys.time()
gtexDtuBenchmark_edgeRdiffsplice <- plyr::llply(
    .data = gtexBenchmarkData,
    .parallel = doParallel,
    .progress = doProgress,
    .inform = TRUE,
    .fun = function(localData) {
        ### Perform DTU analysis
        t0 <- Sys.time()
        localRes <- edgeR_diffsplice_DTU(
            countData  = localData$data,
            tx2gene    = localData$metaInfo,
            sampleData = localData$design
        )
        testTime <- as.numeric(difftime(Sys.time(), t0, units = 'secs') )

        ### Massage
        localRes$gene_modified <- localData$metaInfo$gene_modified[match(
            localRes$TXNAME, localData$metaInfo$TXNAME
        )]

        ### Return result
        return(
            list(
                dtuAnalysis = localRes,
                runtime = testTime
            )
        )
    }
)
difftime(Sys.time(), tStart)
    
print("start DEXSeq")

tStart <- Sys.time()
gtexDtuBenchmark_DEXSeq <- plyr::llply(
    .data = gtexBenchmarkData,
    .parallel = doParallel,
    .progress = doProgress,
    .inform = TRUE,
    .fun = function(localData) {
            
        if(ncol(localData$data) > 10) {
            return(NULL) # do not run DEXSeq for datasets with many samples - too slow
        }
          
        ### Perform DTU analysis
        t0 <- Sys.time()
        localRes <- DEXSeq_DTU(
            countData  = localData$data,
            tx2gene    = localData$metaInfo,
            sampleData = localData$design
        )
        testTime <- as.numeric(difftime(Sys.time(), t0, units = 'secs') )

        ### Massage
        localRes$gene_modified <- localData$metaInfo$gene_modified[match(
            localRes$TXNAME, localData$metaInfo$TXNAME
        )]

        ### Return result
        return(
            list(
                dtuAnalysis = localRes,
                runtime = testTime
            )
        )
    }
)
difftime(Sys.time(), tStart)
    
print("start DRIMSeq")

tStart <- Sys.time()
gtexDtuBenchmark_DRIMSeq <- plyr::llply(
    .data = gtexBenchmarkData,
    .parallel = doParallel,
    .progress = doProgress,
    .inform = TRUE,
    .fun = function(localData) {
          
        if(ncol(localData$data) > 10) {
            return(NULL) # do not run DRIMSeq for datasets with many samples - too slow
        }
          
        ### Perform DTU analysis
        t0 <- Sys.time()
        localRes <- DRIMSeq_DTU(
            countData  = localData$data,
            tx2gene    = localData$metaInfo,
            sampleData = localData$design
        )
        testTime <- as.numeric( difftime(Sys.time(), t0, units = 'secs') )

        ### Massage
        localRes$gene_modified <- localData$metaInfo$gene_modified[match(
            localRes$TXNAME, localData$metaInfo$TXNAME
        )]

        ### Return result
        return(
            list(
                dtuAnalysis = localRes,
                runtime = testTime
            )
        )
    }
)
difftime(Sys.time(), tStart)
    
     
print("start NBSplice")

tStart <- Sys.time()
gtexDtuBenchmark_NBSplice <- plyr::llply(
    .data = gtexBenchmarkData,
    .parallel = doParallel,
    .progress = doProgress,
    .inform = TRUE,
    .fun = function(localData) {
          
        if(ncol(localData$data) > 10) {
              return(NULL) # do not run NBSPlice for datasets with many samples - too slow
        }
          
        ### Perform DTU analysis
        t0 <- Sys.time()
        localRes <- NBSplice_DTU(
            countData  = localData$data,
            tx2gene    = localData$metaInfo,
            sampleData = localData$design,
            quiet=FALSE
        )
        testTime <- as.numeric(difftime(Sys.time(), t0, units = 'secs') )

        ### Massage
        localRes$gene_modified <- localData$metaInfo$gene_modified[match(
            localRes$TXNAME, localData$metaInfo$TXNAME
        )]

        ### Return result
        return(
            list(
                dtuAnalysis = localRes,
                runtime = testTime
            )
        )
    }
)
difftime(Sys.time(), tStart)

### add method name to list names for easy post-analysis
names(gtexDtuBenchmark_satuRn) <- paste0('satuRn_',names(gtexDtuBenchmark_satuRn))
names(gtexDtuBenchmark_DoubleExpSeq) <- paste0('DoubleExpSeq_', names(gtexDtuBenchmark_DoubleExpSeq))
names(gtexDtuBenchmark_limmaDiffsplice) <- paste0('limma_diffsplice_', names(gtexDtuBenchmark_limmaDiffsplice))
names(gtexDtuBenchmark_edgeRdiffsplice) <- paste0('edgeR_diffsplice_', names(gtexDtuBenchmark_edgeRdiffsplice))
names(gtexDtuBenchmark_DEXSeq) <- paste0('DEXSeq_', names(gtexDtuBenchmark_DEXSeq))
names(gtexDtuBenchmark_DRIMSeq) <- paste0('DRIMSeq_', names(gtexDtuBenchmark_DRIMSeq))
names(gtexDtuBenchmark_NBSplice) <- paste0('NBSplice_', names(gtexDtuBenchmark_NBSplice))

### Save result
save(gtexDtuBenchmark_satuRn,
    gtexDtuBenchmark_limmaDiffsplice,
    gtexDtuBenchmark_edgeRdiffsplice,
    gtexDtuBenchmark_DoubleExpSeq,
    gtexDtuBenchmark_DEXSeq,
    gtexDtuBenchmark_DRIMSeq,
    gtexDtuBenchmark_NBSplice,
    file=paste0(wd,'/Data/Gtex_workingData/03_GTEx_DTU_results_count.Rdata'))
```




