---
title: "readResults_evenNewer"
output: html_document
---

Load libraries

```{r, message=FALSE}
library(ggplot2)
library(tidyverse)
```

Read all results

```{r}
# read quasiBinomial results
load("/Users/jg/Desktop/PhD/DTU_project/Github/dtuPaper/Benchmarks/Scalability/results/finalOutput_quasiBinomial_1.RData")
load("/Users/jg/Desktop/PhD/DTU_project/Github/dtuPaper/Benchmarks/Scalability/results/finalOutput_quasiBinomial_2.RData")

# read limmaDiffsplice results
load("/Users/jg/Desktop/PhD/DTU_project/Github/dtuPaper/Benchmarks/Scalability/results/finalOutput_limmaDiffsplice_1.RData")
load("/Users/jg/Desktop/PhD/DTU_project/Github/dtuPaper/Benchmarks/Scalability/results/finalOutput_limmaDiffsplice_2.RData")

# read edgeRDiffsplice results
load("/Users/jg/Desktop/PhD/DTU_project/Github/dtuPaper/Benchmarks/Scalability/results/finalOutput_edgeRDiffsplice_1.RData")
load("/Users/jg/Desktop/PhD/DTU_project/Github/dtuPaper/Benchmarks/Scalability/results/finalOutput_edgeRDiffsplice_2.RData")

# read DRIMSeq results
load("/Users/jg/Desktop/PhD/DTU_project/Github/dtuPaper/Benchmarks/Scalability/results/finalOutput_DRIMSeq_1.RData")
load("/Users/jg/Desktop/PhD/DTU_project/Github/dtuPaper/Benchmarks/Scalability/results/finalOutput_DRIMSeq_2.RData")

# read DoubleExpSeq results
load("/Users/jg/Desktop/PhD/DTU_project/Github/dtuPaper/Benchmarks/Scalability/results/finalOutput_DoubleExpSeq_1.RData")
load("/Users/jg/Desktop/PhD/DTU_project/Github/dtuPaper/Benchmarks/Scalability/results/finalOutput_DoubleExpSeq_2.RData")

# read DEXSeq results
load("/Users/jg/Desktop/PhD/DTU_project/Github/dtuPaper/Benchmarks/Scalability/results/finalOutput_DEXSeq_2.RData")
load("/Users/jg/Desktop/PhD/DTU_project/Github/dtuPaper/Benchmarks/Scalability/results/finalOutput_DEXSeq_3.RData")
load("/Users/jg/Desktop/PhD/DTU_project/Github/dtuPaper/Benchmarks/Scalability/results/finalOutput_DEXSeq_4.RData")

# read BANDITS results
load("/Users/jg/Desktop/PhD/DTU_project/Github/dtuPaper/Benchmarks/Scalability/results/finalOutput_BANDITS_5.RData")
load("/Users/jg/Desktop/PhD/DTU_project/Github/dtuPaper/Benchmarks/Scalability/results/finalOutput_BANDITS_6.RData")
```

Concatenate all results

```{r}
finalOutput_all <- c(finalOutput_quasiBinomial_1,finalOutput_quasiBinomial_2,finalOutput_limmaDiffsplice_1,finalOutput_limmaDiffsplice_2,finalOutput_edgeRDiffsplice_1,finalOutput_edgeRDiffsplice_2,finalOutput_DRIMSeq_1,finalOutput_DRIMSeq_2,finalOutput_DoubleExpSeq_1,finalOutput_DoubleExpSeq_2,finalOutput_DEXSeq_2,finalOutput_DEXSeq_3,finalOutput_DEXSeq_4,finalOutput_BANDITS_5,finalOutput_BANDITS_6)
rm(list=setdiff(ls(), "finalOutput_all"))
```

```{r}
full_dataframe <-  as.data.frame(matrix(nrow = length(finalOutput_all), ncol=10))
colnames(full_dataframe) <- c("method", "groupSize", "TXs", "TXs_round", "user", "system", "elapsed", "DTU", "removed", "memory")

full_dataframe$method <- rep(c("satuRn","limmaDiffsplice","edgeRDiffsplice","DRIMSeq","DoubleExpSeq","DEXSeq","BANDITS"),times=c(24,24,24,24,24,16,7)) # add method labels

round_to <- function(x, to = 1000) round(x/to)*to

# get data in dataframe format
for (i in seq_len(nrow(full_dataframe))) {
  full_dataframe$groupSize[i] <- finalOutput_all[[i]]$info$size
  full_dataframe$TXs[i] <- finalOutput_all[[i]]$info$TXs
  full_dataframe$TXs_round[i] <- round_to(full_dataframe$TXs[i])
  full_dataframe$user[i] <- unname(finalOutput_all[[i]]$timing[1])
  full_dataframe$system[i] <- unname(finalOutput_all[[i]]$timing[2])
  full_dataframe$elapsed[i] <- unname(finalOutput_all[[i]]$timing[3])
  full_dataframe$DTU[i] <- ifelse(is.null(finalOutput_all[[i]]$result),NA,finalOutput_all[[i]]$result)
  full_dataframe$removed[i] <- finalOutput_all[[i]]$removed
  full_dataframe$memory[i] <- finalOutput_all[[i]]$memory[4]
}
```

---

# Scalability w.r.t. number of cells

```{r}
data_30K <- full_dataframe[which(full_dataframe$TXs_round == 30000),]
```

```{r}
# scalability w.r.t. number of cells
ggplot(data = data_30K, aes(x=groupSize,y=elapsed/60,color=method)) +
  geom_line() +
  geom_point() +
  scale_color_manual(values=c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2","black")) +
  theme_bw() +
  ylab("elapsed  time (min)") + 
  xlab("number of cells per group")
```

```{r}
# scalability w.r.t. number of cells - zoom
ggplot(data = data_30K[-which(data_30K$method %in% c("DEXSeq","DRIMSeq")),], aes(x=groupSize,y=elapsed/60,color=method)) +
  geom_line() +
  geom_point() +
  scale_color_manual(values=c("#56B4E9", "#F0E442", "#0072B2","black")) +
  theme_bw() +
  ylab("elapsed  time (min)") + 
  xlab("number of cells per group")
```

--- 

# Scalability w.r.t. number of transcripts

```{r}
data_16cells <- full_dataframe[which(full_dataframe$groupSize == 16),]
```

```{r}
ggplot(data = data_16cells, aes(x=TXs,y=elapsed/60,color=method)) +
  geom_line() +
  geom_point() +
  scale_color_manual(values=c("#CC79A7", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2","black")) +
  theme_bw() +
  ylab("elapsed  time (min)") + 
  xlab("number of transcripts")
```

```{r}
# scalability w.r.t. number of transcripts
ggplot(data = data_16cells[-which(data_16cells$method %in% c("BANDITS", "DEXSeq","DRIMSeq")),], aes(x=TXs,y=elapsed/60,color=method)) +
  geom_line() +
  geom_point() +
  scale_color_manual(values=c("#CC79A7", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2","black")) +
  theme_bw() +
  ylab("elapsed  time (min)") + 
  xlab("number of transcripts")
```
