---
title: "Dmelanogaster_ECC_raw_visualize"
output: html_document
---

```{r,message=FALSE}
library(tidyverse)
library(iCOBRA)
```

Load data

```{r}
if(TRUE) {
    load(file='01_Dmelanogaster_benchmark_data_ECC_count.Rdata')
    load(file='02_Dmelanogaster_benchmark_DTU_analysis_ECC_count.Rdata')
    
    # load(file='01_Dmelanogaster_benchmark_data_ECC_tpm.Rdata')
    # load(file='02_Dmelanogaster_benchmark_DTU_analysis_ECC_tpm.Rdata')
    
    #load(file='02_Dmelanogaster_benchmark_DTU_analysis_ECC_count_BANDITS.Rdata')
    #load(file='01_Dmelanogaster_benchmark_data_ECC_tpm.Rdata')
    #load(file='02_Dmelanogaster_benchmark_DTU_analysis_ECC_subset_tpm.Rdata')
  
    DmelanogasterBenchmark <- c(
        DmDtuBenchmark_quasiBinomial,
        DmDtuBenchmark_DoubleExpSeq,
        DmDtuBenchmark_limmaDiffsplice,
        DmDtuBenchmark_edgeRdiffsplice,
        DmDtuBenchmark_DEXSeq,
        DmDtuBenchmark_DRIMSeq,
        DmDtuBenchmark_NBSplice
    )
    
    ### Remove empty enteries (due to not tested - aka to many samples for reasonable runtime)
    DmelanogasterBenchmark  <- DmelanogasterBenchmark[which(
        sapply(DmelanogasterBenchmark, function(x) ! is.null(x$dtuAnalysis))
    )]
    
    rm(DmDtuBenchmark_quasiBinomial,
        DmDtuBenchmark_limmaDiffsplice,
        DmDtuBenchmark_DEXSeq,
        DmDtuBenchmark_DRIMSeq,
        DmDtuBenchmark_edgeRdiffsplice,
        DmDtuBenchmark_NBSplice,
        DmDtuBenchmark_DoubleExpSeq)
    invisible(gc())
}

truth_file <- read.table(file = "/Users/jg/Desktop/PhD/DTU_project/Github/dtuPaper/Data/Dmelanogaster_data/truth_Dmelanogaster.txt", sep = "\t", header = TRUE)
```

```{r}
get_pvalues <- function(dataset,nmethods) {
  
  pvalues <- matrix(data=NA, nrow=nrow(dataset[[1]]$dtuAnalysis), ncol=nmethods)
  rownames(pvalues) <- as.character(dataset[[1]]$dtuAnalysis$TXNAME)
  
  for (i in 1:nmethods) {
    pvalues_new <- data.frame(dataset[[i]]$dtuAnalysis$p_value)
    rownames(pvalues_new) <-as.character(dataset[[i]]$dtuAnalysis$TXNAME)
    colnames(pvalues_new) <- names(dataset)[i]

    pvalues[,i] <- pvalues_new[match(rownames(pvalues),rownames(pvalues_new)),1]
  }
  
  pvalues <- apply(pvalues, 2, as.numeric)
  rownames(pvalues) <- as.character(dataset[[1]]$dtuAnalysis$TXNAME)
  pvalues <- as.data.frame(pvalues)
  pvalues <- pvalues[order(rownames(pvalues)),]
  
  colnames(pvalues) <- c("quasiBinomial", "DoubleExpSeq", "limma_diffsplice", "edgeR_diffsplice", "DEXSeq", "DRIMSeq", "NBSplice")
  
  return(pvalues)
}
```

```{r}
visualize_datasets <- function(dataset,nFilters,nmethods) {
  
    print(paste("This function will generate", nFilters, "plots"))

    ##  We must select the correct dataframes from the list, based on the list names
    selection <- c("filterLenient","filterStringent")

## Generate and store the data for the plots
  resList <- c()
  for (j in 1:nFilters) {
      print(j) # print progress
      Dmelanogaster_current <- DmelanogasterBenchmark[grepl(selection[j], names(DmelanogasterBenchmark))]
      
      #Dmelanogaster_current[["BANDITS_filterStringent"]] <- DmDtuBenchmark_BANDITS$BANDITS_filterStringent

      pvalues <- get_pvalues(dataset=Dmelanogaster_current,nmethods=7)
      
      truth_file_current <- truth_file[truth_file$transcript_id %in% rownames(pvalues),]
      truth_file_current <- truth_file_current[order(truth_file_current$transcript_id),]
      rownames(truth_file_current) <- truth_file_current$transcript_id

      cobra <- COBRAData(pval = pvalues, truth = truth_file_current)
      cobra <- calculate_adjp(cobra)
      cobra1perf <- calculate_performance(cobra, binary_truth = "transcript_ds_status", cont_truth = "none", splv = "none", aspects = c("fdrtpr", "fdrtprcurve", "overlap"))

      cobraplot <- prepare_data_for_plot(cobra1perf, colorscheme = "Dark2", facetted = TRUE)
      new_col <- c(rep(c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00","black", "#999999"),4),rep("white",16))
      names(new_col) <- names(cobraplot@plotcolors)
      cobraplot@plotcolors <- new_col
      
      plot_full <- plot_fdrtprcurve(cobraplot, xaxisrange = c(0, 0.35), yaxisrange = c(0,0.85))
      
      titles <- c("5 versus 5 - edgeR filter","5 versus 5 - DRIMSeq filter")
      current_title <- titles[j]
      
      plot_full <- plot_full + 
      ggtitle(current_title) +
      theme(strip.background = element_blank(),
            strip.text.x = element_blank(),
            plot.title = element_text(size=10),
            axis.text.x = element_text(size = 10),
            axis.text.y = element_text(size = 10),
            axis.title.x = element_text(size = 10),
            axis.title.y = element_text(size = 10))
      
      png(paste("/Users/jg/Desktop/PhD/DTU_project/Github/dtuPaper/Results/Dmelanogaster_benchmark/plot_icobra_counts_", j, ".png", sep = ""),
      width     = 5.5,
      height    = 4.5,
      units     = "in",
      res       = 200,
      pointsize = 4) # start export
      print(plot_full)
      dev.off()
  }
}
```

```{r}
visualize_datasets(dataset=DmelanogasterBenchmark,
                   nFilters=2,
                   nmethods=7)
```
